
### /datauploads - default flow
POST {{base-url}}/datauploads
Content-Type: application/json

{
  "name": "Dataset xyz - Upload sjdfk",
  "description": "Upload for dataset xyz",
  "uploader": "jane doe",
  "files": [
    {
      "name": "filename1.csv",
      "size": 1000
    },
    {
      "name": "filename2.csv",
      "size": 2000
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### /datauploads - with comments
POST {{base-url}}/datauploads
Content-Type: application/json

{
  "name": "Dataset xyz - Upload with comments",
  "description": "Upload for dataset 2",
  "uploader": "jane doe",
  "files": [
    {
      "name": "filename1.csv",
      "size": 1000
    }
  ],
  "comments": [
    {
      "content": "comment 1 asdfsdfdsf",
      "commenter": "john doe"
    },
    {
      "content": "comment 2 asdfsdfdsf",
      "commenter": "jane doe"
    }

  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}


### GET /datauploads - default flow
GET {{base-url}}/datauploads
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
