
### /datauploads - default flow
POST {{base-url}}/repos
Content-Type: application/json

{
  "data_upload_id": "xyz",
  "name": "Dataset 1 - Upload 1 repo"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

###
