
### validateDataPackage - default flow
PUT {{base-url}}/validateDataPackage
Content-Type: application/json

{
  "resources" : [
    {
      "name" : "example",
      "profile" : "tabular-data-resource",
      "schema" : {
        "fielsds" : [
          {
            "name" : "height",
            "type" : "integer"
          },
          {
            "name" : "age",
            "type" : "integer"
          },
          {
            "name" : "name",
            "type" : "string"
          }
        ]
      }
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### POST /schemas - default flow
POST {{base-url}}/schemas
Content-Type: application/json

{
  "fields" :
  [
    {
      "name" : "height",
      "type" : "integer"
    },
    {
      "name" : "age",
      "type" : "integer"
    },
    {
      "name" : "name",
      "type" : "string"
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### POST /schemas - mispelled "fields" property
POST {{base-url}}/schemas
Content-Type: application/json

{
  "fieljkjlkds" :
  [
    {
      "name" : "height",
      "type" : "integer"
    },
    {
      "name" : "age",
      "type" : "integer"
    },
    {
      "name" : "name",
      "type" : "string"
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### POST /schemas - empty field array
POST {{base-url}}/schemas
Content-Type: application/json

{
  "fields" : []
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### POST /schemas - mispelled required column def "name" attribute
POST {{base-url}}/schemas
Content-Type: application/json

{
  "fields" :
  [
    {
      "name" : "height",
      "type" : "integer"
    },
    {
      "nasdfdsfme" : "age",
      "type" : "integer"
    },
    {
      "name" : "name",
      "type" : "string"
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### POST /schemas - missing required column def "name" attribute
POST {{base-url}}/schemas
Content-Type: application/json

{
  "fields" :
  [
    {
      "name" : "height",
      "type" : "integer"
    },
    {
      "name" : "age",
      "type" : "integer"
    },
    {
      "type" : "string"
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### POST /schemas - multiple invalid column defs
POST {{base-url}}/schemas
Content-Type: application/json

{
  "fields" :
  [
    {
      "name" : "height",
      "type" : "integer"
    },
    {
      "nassme" : "age",
      "type" : "integer"
    },
    {
      "type" : "string"
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

###
