
###
GET {{forum-api-base-url}}/comment/{{data-set-upload-1-topic-id}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
POST {{forum-api-base-url}}/comment/{{data-set-upload-1-topic-id}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "comment": "test comment 4"
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
