
### /datauploads - default flow
POST {{base-url}}/datauploads
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Dataset xyz - Upload sjdfk",
  "description": "Upload for dataset xyz",
  "uploader": "jane doe",
  "files": [
    {
      "name": "filename1.csv",
      "size": 1000
    },
    {
      "name": "filename2.csv",
      "size": 2000
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### /datauploads - missing required property
POST {{base-url}}/datauploads
Content-Type: application/json

{
  "description": "Upload for dataset xyz",
  "uploader": "jane doe",
  "files": [
    {
      "name": "filename1.csv",
      "size": 1000
    },
    {
      "name": "filename2.csv",
      "size": 2000
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 500, "Response status is not 500");
    });
%}


### PUT /datauploads/:dataUploadId  - default flow
PUT {{base-url}}/datauploads/{{dataset-1-upload-1-id}}
Content-Type: application/json

{
  "name": "Dataset xyz - Upload with comments",
  "description": "Upload for dataset 2",
  "files": [
    {
      "name": "filename1.csv",
      "size": 1000
    }
  ],
  "opened_by_approver": true
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### GET /datauploads - default flow
GET {{base-url}}/datauploads
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### GET /dataupload/:dataUploadId - default flow
GET {{base-url}}/datauploads/{{dataset-1-upload-1-id}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
