
#####################################################################################################################
#
#   Dataset 1 - Upload 1
#
#####################################################################################################################

### /metadatarevisions - default flow
POST {{base-url}}/metadatarevisions
Content-Type: application/json

{
  "repo_branch_id": "xyz",
  "type": "tabular_data_package",
  "revision_number": 1,
  "change_summary": "Initial upload",
  "updater": "Jane Doe",
  "content": {}
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

###





