
### /datauploads - default flow
POST {{base-url}}/repobranches
Content-Type: application/json

{
  "repo_id": "xyz",
  "type": "standard",
  "name": "edition/standard",
  "description": "Dataset 1 - Upload 1 repo branch",
  "revisions": []
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}


