
###
GET {{forum-api-base-url}}/permission
Authorization: Bearer {{jwtAdmin}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
POST {{forum-api-base-url}}/permission
Authorization: Bearer {{jwtAdmin}}
Content-Type: application/json

{
  "priority": 0,
  "allow": true,
  "topic_id": "5e9f3c896103d6d55dce9060",
  "group_ids": [
    "metadata_approver_1_dip"
   ]
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
POST {{forum-api-base-url}}/
Authorization: Bearer {{jwtAdmin}}
Content-Type: application/json

{
  "name": "{{dataset-1-upload-2-id}}"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
