name: "Frontend"
on: ["push", "pull_request"]
jobs:
  audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: audit
        run: npm audit