name: "Frontend"
on: ["push", "pull_request"]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: change to frontend
        run: cd frontend
      - name: install dependencies
        run: npm ci
      - name: audit
        run: npm audit