name: "Metadata Curator"
on: ["push", "pull_request", "release"]
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  QUAYIO_PASSWORD: ${{ secrets.QUAYIO_PASSWORD }}
  QUAYIO_USERNAME: ${{ secrets.QUAYIO_USERNAME }}
jobs:
  audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: audit
        if: github.event_name != 'release' || github.event.action != 'created'
        run: npm audit
  
  unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: test
        run: |
          cp config/default.json.example config/default.json
          npm test

  quay_io_backend:
    runs-on: ubuntu-latest
    needs: ["unit_test", "audit"]
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@v2

      - name: push to quay
        run: |
          export BRANCH=${GITHUB_REF##*/}
          chmod ugo+x ./docker_quayio_push
          ./docker_quayio_push metadata_curator_api
  
  quay_io_frontend:
    runs-on: ubuntu-latest
    needs: ["quay_io_backend"]
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2

      - name: push to quay
        run: |
          export BRANCH=${GITHUB_REF##*/}
          chmod ugo+x ./docker_quayio_push
          ./docker_quayio_push metadata_curator_ui

  
  deploy_backend:
    runs-on: ubuntu-latest
    needs: ["quay_io_backend"]
    if: success() && ( (github.event_name == 'release' && github.event.action == 'created') || (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/develop') )
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_DEPLOY_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_DEPLOY_PASSWORD }}
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: push to quay
        run: |
          export BRANCH=${GITHUB_REF##*/}
          chmod ugo+x ./docker_push
          ./docker_push metadata_curator_api

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: ["deploy_backend"]
    if: success() && ( (github.event_name == 'release' && github.event.action == 'created') || (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/develop') )
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_DEPLOY_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_DEPLOY_PASSWORD }}
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: push to quay
        run: |
          export BRANCH=${GITHUB_REF##*/}
          chmod ugo+x ./docker_push
          ./docker_push metadata_curator_ui

  integration_tests:
    runs-on: ubuntu-latest
    #needs: ["quay_io_backend", "quay_io_frontend"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: terraform
        env:
          TERRAFORM_VERSION: "0.13.6"
          KATALON_VERSION: "6.0.5"
        run: |
          export WD=`pwd`
          export BRANCH=${GITHUB_REF##*/}
          cd /tmp
          wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip -o /tmp/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          rm -rf /tmp/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          chmod +x terraform
          alias terraform='/tmp/terraform'
          cd $WD/terraform
          mkdir _tmp
          python scripts/prepare_images_variable.py
          cp terraform.tfvars.example terraform.tfvars
          export DOCKER_REGISTRY_USER=$DOCKER_USERNAME
          export DOCKER_REGISTRY_PASS=$DOCKER_PASSWORD
          chmod 777 ./scripts/keycloak-setup.sh
          echo provider "docker" { > docker.tf
          echo registry_auth { >> docker.tf
          echo address  = "quay.io:8181" >> docker.tf
          echo username = "${QUAYIO_USERNAME}" >> docker.tf
          echo password = "${QUAYIO_PASSWORD}" >> docker.tf
          echo } >> docker.tf
          echo } >> docker.tf
          cat docker.tf
          terraform init
          terraform apply -var hostRootPath=`pwd`/_tmp -auto-approve